#!/bin/bash

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. make/include/colors

printf "%b==> Generating mocks %b\n" "${OK_COLOR}" "${ERROR_COLOR}"

pushd token/testing && mockgen --source ../token.go --destination=token_mock.go && popd

pushd app/puppet-access/api/testing && mockgen --source ../client.go --destination=client_mock.go && popd
pushd app/puppet-access/api/client/operations/testing && mockgen --source ../operations_client.go --destination=operations_client_mock.go && popd

pushd app/puppet-code/api/testing && mockgen --source ../client.go --destination=client_mock.go && popd
pushd app/puppet-code/api/client/operations/testing && mockgen --source ../operations_client.go --destination=operations_client_mock.go && popd

pushd app/puppetdb-cli/api/testing && mockgen --source ../client.go --destination=client_mock.go && popd
pushd app/puppetdb-cli/api/client/operations/testing && mockgen --source ../operations_client.go --destination=operations_client_mock.go && popd

printf "%b" "${NO_COLOR}"
