---
name: go-check
on:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    strategy:
      matrix:
        go-version: [1.25.0]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: ./src/github.com/puppetlabs/pe-sdk-go/
    - name: Install pre-requisites
      if: matrix.platform == 'ubuntu-latest'
      run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install golang.org/x/lint/golint@latest
    - name: Format
      if: matrix.platform == 'ubuntu-latest'
      run: cd ./src/github.com/puppetlabs/pe-sdk-go && make format
    - name: Vet
      if: matrix.platform == 'ubuntu-latest'
      run: cd ./src/github.com/puppetlabs/pe-sdk-go && make vet
    - name: Lint
      if: matrix.platform == 'ubuntu-latest'
      run: cd ./src/github.com/puppetlabs/pe-sdk-go && make lint
    - name: Test
      run: cd ./src/github.com/puppetlabs/pe-sdk-go && make test

